version: '3.8'
services:
  app:
    build: rolldice
    ports:
      - "8000:8080"
    volumes:
      - ./rolldice:/app  # Mounts the application directory to /app inside the container
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    command: ["--config=/etc/otel/config.yaml"]
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - NEW_RELIC_LICENSE_KEY
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
